version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yieldsense_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://yashraj191220_db_user:S6fQWhT99rohAkli@cropyiled.slmdhrd.mongodb.net/yieldsense_ai?retryWrites=true&w=majority
      - DATABASE_NAME=yieldsense_ai
      - JWT_SECRET=yieldsense_secret_key_2026_super_secure
      - ADMIN_SECRET_KEY=ADMIN@YIELDSENSE2024
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yieldsense_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: yieldsense_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
